"""Add multi-user support fields

Revision ID: e3f7ee973dd1
Revises: 
Create Date: 2026-03-25 22:05:47.260504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f7ee973dd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    
    # Add columns as nullable first to handle existing data
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Update existing users with placeholder values (they should be corrected later)
    # We use a placeholder that matches the unique constraint if multiple users exist (concatenating something)
    # But since there is likely only one user 'kikin', this works:
    op.execute("UPDATE usuarios SET email = 'admin@labbitacora.com', is_admin = true, is_active = true")
    
    # Now enforce NOT NULL for admin/active but leave email nullable
    op.alter_column('usuarios', 'is_admin', nullable=False)
    op.alter_column('usuarios', 'is_active', nullable=False)
    
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'is_admin')
    op.drop_column('usuarios', 'email')
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
