"""fase_5_proyectos_y_colaboracion

Revision ID: e9d701c8a0c1
Revises: e3f7ee973dd1
Create Date: 2026-03-26 01:13:05.297049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d701c8a0c1'
down_revision: Union[str, None] = 'e3f7ee973dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('proyecto_miembros',
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proyecto_id', 'usuario_id')
    )
    op.add_column('practicas', sa.Column('proyecto_id', sa.UUID(), nullable=True))
    op.add_column('practicas', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_foreign_key(None, 'practicas', 'proyectos', ['proyecto_id'], ['id'], ondelete='SET NULL')
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'practicas', type_='foreignkey')
    op.drop_column('practicas', 'is_public')
    op.drop_column('practicas', 'proyecto_id')
    op.drop_table('proyecto_miembros')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
